### ISSUE TITLE
Tracking Issues of Basic Docs

### ISSUE THREAD

**Issue by PsiACE** [PsiACE/marianne#1]
- [ ] How to Use
- [ ] How to Dev
- [ ] How to Contribute
- [ ] Design & Goals
